blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/jomaxso/Reshape/blob/main/README.md
    about: Check the documentation for usage guides and examples
  - name: ğŸ¤ Contributing Guide
    url: https://github.com/jomaxso/Reshape/blob/main/docs/CONTRIBUTING.md
    about: Learn how to contribute to the project
